### ISSUE TITLE
Ingesting URLs 

### ISSUE THREAD

**Issue by Ansel-Hong** [mjordan/islandora_workbench#230]
When ingesting URLs into a field with field_type "Link", the field seems to be ignored while other fields are ingested accordingly

The "field_link" field is of type "Link" in Drupal.

[example.pdf](https://github.com/mjordan/islandora_workbench/files/6024970/example.pdf)

**Comment by mjordan** [comment]
Thanks, I'll investigate.

**Comment by mjordan** [comment]
@Ansel-Hong I hadn't looked at the JSON structure of a link field before. It's like this:

```
"field_test_link_field":[{"uri":"https:\/\/www.lib.sfu.ca","title":"SFU Library Website","options":[]}]
```
which shows there are two parts we need to deal with in CSV, the 'uri' and the 'title' (can't tell what 'options' is for but that's fine for now). Workbench will need to convert CSV data for these fields into this structure to push up to Drupal. So far, for multipart (in this case, uri and title) values in the input CSV, Workbench has used a `:` to separate the parts. We can't use that here since URLs have a `:` in them. Maybe a `^` is suitable, e.g. `https://duckduckgo.com/^DuckDuckGo`.

Once we work out how to enter the URL and title in the CSV, I'll need to do a bit of coding to accommodate this new field structure. Shouldn't be a lot though.

**Comment by mjordan** [comment]
Note to @mjordan: field_config says "field_type":"link".

**Comment by mjordan** [comment]
We should allow for no title. For example, if the uri/title delimiter is not present, use the uri as the title.

**Comment by Ansel-Hong** [comment]
I'll also try to work on it myself, can you give me some pointers to start? 
Thanks.

**Comment by mjordan** [comment]
@Ansel-Hong I appreciate the offer but I've already started work on this. I'm about half way through converting all Drupal field type handlers to objects (see https://github.com/mjordan/islandora_workbench/issues/72) and the "link" field type is the first one added since I started this work. I'd prefer to finish this one, and document it so others can add new field types as needed. If someone else came in half way through this shift to implementing new fields as objects I'm not sure I would be able to support you very well, since I haven' validated the new pattern I've established in this implementation.

Like I said, I really appreciate the offer but I think it's best that I complete this one and document how to do it first.

**Comment by mjordan** [comment]
@Ansel-Hong you now be able to use Link fields in `create` and `update` tasks. Please pull in the latest changes to the main branch and test. The documentation for Link fields in is the "Link fields" section of https://mjordan.github.io/islandora_workbench_docs/fields/ .

**Comment by mjordan** [comment]
@Ansel-Hong I see you :+1: there - did you test this?

**Comment by Ansel-Hong** [comment]
Yes I did the create and update tasks works for Link fields

**Comment by mjordan** [comment]
Thanks for opening this issue and testing!
