### ISSUE TITLE
Support for sites preferencing the non-base Drupal title field for title metadata

### ISSUE THREAD

**Issue by kspurgin** [mjordan/islandora_workbench#295]
Currently a value for the Drupal base `title` property/field is required by Islandora Workbench. 

Given that sites are using a variety of strategies to be able to record longer than 255-character titles, or more complex title information in Islandora without manually also filling in the Drupal title property*, the need here is for Workbench to be able to ingest metadata into those sites using whatever full/main title field a site is using. 

Put another way: I would like to be able to import  `field_my_long_title_data` as my title data and not also have to configure/derive a separate `title` field value from my full title data field in my spreadsheet. 

I believe the idea put forth in the 2021-06-29 open meeting for this was to indicate via configuration which column/field an underlying Drupal `title` should be derived from if a plain `title` column is not included. (More generalizably, introducing a "copy value from" setting where one column can be copied/derived from another)

(please edit/update this issue for clarity/appropriate terminology if I have not captured any of this well!)

* Examples:
  * Many sites are using [title_length module](https://www.drupal.org/project/title_length)
  * At LYRASIS we are developing a custom "Typed Labeled Title" field type (specified [here](https://github.com/lyrasis/islandora8-metadata/blob/main/field_types/typed_labeled_title.adoc)). The Drupal title label is hidden from display and forms in our instances. Users will populate the Typed Labeled Title in forms and that is the field we will target in our migrations into I8.  A value for the Drupal title label is automatically derived from the `typed_labeled_title/title` property.

**Comment by seth-shaw-unlv** [comment]
I believe longer_titles was only for Drupal 5. The module we use to extend our title property length is [title_length](https://www.drupal.org/project/title_length).

**Comment by mjordan** [comment]
This is a great improvement. I'll move onto it once I close a couple of other other feature requests. Thanks!

**Comment by kspurgin** [comment]
Drupal 5!! (updating that link, thanks)

(I need a Greasemonkey script that puts a big X over any page I look at that indicates pre-Drupal-8 content)

**Comment by mjordan** [comment]
Until we find a way to let the Workbench Integration Module introspect the configured maximum length of the title, I can add a configuration option that you could set to override the default length of 255 characters. I would also document this option so that it's clear how you would determine what a valid maximum length is for your particular Drupal. @kspurgin are you OK with this approach?

**Comment by kspurgin** [comment]
Sounds workable. Thanks!

**Comment by mjordan** [comment]
OK, I've pushed this change up to the main branch, and the docs have been updated. I've also removed the `validate_title_length` config option since it was obsolete anyway - the length of all text fields is checked against their database defnitions (although 'title' is a special field and you can't check its database definition, or at least in any way I have found.
