### ISSUE TITLE
Add configuration options for link titles when exporting metadata to CSV

### ISSUE THREAD

**Issue by Gii2000** [mjordan/islandora_workbench#604]
Recently, we noticed when exporting metadata into CSV that some of our ARKs have %% at the end (e.g. `http://n2t.net/ark:/62930/d1sw7m%%`), which seems to be caused by some of the `title` fields in our permalinks being an empty string.

Even if the `title` field wasn't blank, it would be nice to just have the URL exported. This sounds like a perfect case for creating a configuration option, say `export_links_with_title` defaulted to true (although, I think we would prefer it always being false).

Additionally, if we did want the `title` of the links, it would be more ideal if it was exported into its own column, although that might take more effort than it's worth.

I created a pull request that simply doesn't append %% for empty link titles, and I'll let you decide how far you want to take this issue.

**Comment by mjordan** [comment]
Thanks! This looks good. I'll merge your PR. I like your suggestion of a config setting to let users decide if they also want the title. But, I'm not in favor of putting the URL and title in separate columns, since the output CSV is supposed to be in a format that is compatible with Workbench's input CSV (so you can do round-trip updates). But, this option might be a good topic for discussion in the slack channel or in a separate Github issue.
