### ISSUE TITLE
Workbench reports multiple node IDs exist for parent even after one of them was deleted

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#647]
I am running issue_613 branch. I ran Workbench and it reported an issue with an additional file setting, so I stopped the ingest and deleted the one node that had been created (node ID 5616). Then I ran it again, but I get this warning:
```
(awesome) Born-Digitals-MacBook-Air-4:islandora_workbench Dara$ ./workbench --config create_sample3.yml
OK, connection to Drupal at https://diglib-staging.amphilsoc.org verified.
"Create" task started using config file create_sample3.yml.
Node for "Mss.B.F826 - William Parker Foulke Papers, 1840-1865" (record text:Mss.B.F826) created at https://diglib-staging.amphilsoc.org/node/5617.
+ No files specified in CSV for row text:Mss.B.F826.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "text:Mss.B.F826" returned multiple node IDs: 5616, 5617. Skpping population of field_member_of.
^CExiting before entire CSV processed. See log for more info.
(awesome) Born-Digitals-MacBook-Air-4:islandora_workbench Dara$
```

Node 5616 was deleted prior to running this ingest. I also have caching turned off in my config:
`enable_http_cache: false`

If there is an error during Workbench's ingest, you stop the run and you correct the error and then restart, Workbench should not still cache the previous ID map (especially if cache is, I thought, turned off?).

I'm also not sure why it reported the issue so many times for one node.

(I removed another note I'd added to this issue because I figured out what was going on there.)

**Comment by mjordan** [comment]
This is the fairly new "CSV ID to node ID map" feature introduced in #607 to enable use of parent IDs from earlier Workbench sessions. If you're not creating compound content from a previous job, you can just delete the db file that contains the map entries. It is named `csv_id_to_node_id_map.db` and it's in your system's temp directory, which is named in your log file. Or, you can add `csv_id_to_node_id_map_path: false` in your config file and Workbench will ignore it.

The situation you're seeing is that you're reingesting the same CSV multiple times. This is a perfectly valid thing to do, but we need to figure out how to 1) allow Workbench to populate the map db so that when you want to use it, the previous session's CSV IDs are present (so we can use them in the current session) and also 2) not have Workbench nag you like you are seeing now. 

I know it's confusing, but this is totally unrelated to the HTTP "cache" that caused problems a few weeks ago. The CSV ID to node ID map is a "cache" (or stored copy) mapping CSV `id` values to their newly created node IDs, to enable lookup of those node IDs to use when creating compound content as discussed in #607. More docs are at https://mjordan.github.io/islandora_workbench_docs/paged_and_compound/#creating-parentchild-relationships-across-workbench-sessions.

**Comment by dara2** [comment]
Thanks - yeah, I didn't think it was related to the caching issues we'd discussed before. Thank you for pointing out where that .db file is, and the config to ignore it. That's super-helpful!

**Comment by mjordan** [comment]
Figuring out how people want to use this feature is something we need to do - I'd very much value your input on that.

**Comment by mjordan** [comment]
Your workbench log should indicate where your temp directory is (it varies by operating system, let's say for example `/tmp` on Linux systems), and unless you set an explicit path in the `csv_id_to_node_id_map_path` setting (e.g. `csv_id_to_node_id_map_path: /home/mark/foo.db`), the file will be `/tmp/csv_id_to_node_id_map.db`. Setting `csv_id_to_node_id_map_path` to `false` tells Workbench to just ignore it completely so that's probably the best thing to do for now. Let me know how it goes.

**Comment by dara2** [comment]
I wonder if it might make sense to have `csv_id_to_node_id_map_path: false` be the default, and if someone wants to reference parent IDs across multiple ingests, they can set it to true? At least for the way I use Workbench, that would be the most helpful (since the number of times I need to fix something and run the ingest again is higher than the number of times I run secondary tasks). But I would love to hear others' opinions. I think the secondary tasks option is a super feature, but maybe doesn't need to be the default - like it's an option that you enable, rather than the assumption.

**Comment by mjordan** [comment]
Yes, it might, but I'd like to get some broad input before we decide. This will work if people know in advance they will want to store the parent CSV ID to node ID mappings, but if we don't populate that db all the time, people won't be able to go back and use those previously collected mappings. But maybe I'm being overly cautious. However, some users may find having a persistent mapping of CSV IDs to node IDs convenient for other purposes. This came up during the migrations community meeting for example. 

The specific error you saw above happened because the same CSV ID was used multiple times (as I said above, it's bound to happen when you load the same CSV a couple times) and in this case the message is supposed to warn you that Workbench can't pick a specific CSV ID to node ID pair to use in creating compound items.

**Comment by dara2** [comment]
Noting that this line in the config, `query_csv_id_to_node_id_map_for_parents: false`, resulted in child nodes not getting attached to parents. 
I commented that out and am back to testing the (updated Friday) issue_613 branch.
My findings are that remote .tif files are now getting ingested, but it is taking a VERY long time to ingest each .tif. Here's what's in my config (I turned cache off altogether because I wasn't sure the state of the caching work in the branch I'm on):
```
task: create
host: "https://diglib-staging.amphilsoc.org/"
username: xxx
password: xxx
input_dir: APS
input_csv: issue_613_test.csv
output_csv: issue_613_test-output.csv
output_csv_include_input_csv: true
allow_missing_files: true
allow_adding_terms: true
validate_title_length: false
strict_check: false
standalone_media_url: true
field_for_media_title: field_pid
field_for_remote_filename: field_pid
delete_tmp_upload: true
enable_http_cache: false
adaptive_pause: 2
adaptive_pause_threshold: 2.5 
# query_csv_id_to_node_id_map_for_parents: false
media_types_override:
  - video: ['avi']
# additional_files:
 # - TEI: 139
```

Do you have any suggestions to speed up pulling over the TIF files? Creating nodes is going at a pretty good speed.

**Comment by mjordan** [comment]
I've pushed some work to the `issue_613` branch (to help testing that branch) that removes the error messages @dara2 reported. It introduces two new config settings that have defaults that should ease the UX while allowing users who want to stricter behaviour: `query_csv_id_to_node_id_map_for_parents` (default of false) and `ignore_duplicate_parent_ids` (default of true). If you ignore them, you won't be hassled with the "Query of ID map for parent ID XXX" warnings above.

**Comment by mjordan** [comment]
Existing config setting:

- `csv_id_to_node_id_map_path`: The path to the CSV ID to node ID map SQLite database. Defaults to `[temp_dir]/csv_id_to_node_id_map.db`. Set to `false` to not use this db.

New config settings:

- `query_csv_id_to_node_id_map_for_parents`: Queries the CSV ID to node ID map when creating compound content. Defaults to `false`. Set to `true` if you want to use parent IDs from previous Workbench sessions.
- `ignore_duplicate_parent_ids`: Tells Workbench to ignore entries in the CSV ID to node ID map that have the same parent ID value. Defaults to `true`. When true, Workbench will use the most recent entry (e.g. the one created during the current session). When set to `false`, Workbench will note duplicate entries (e.g. 'Warning: Query of ID map for parent ID "0002" returned multiple node IDs: (771, 772, 773, 774, 778, 779).') and tell the user that it cannot resolve a single node ID for the parent, and not populate the child's `field_member_of`.
